Update init.c
Fix building on Android

Version 0.1.2 broke building on for Android:

```
cbits-unix/init.c:11:10: error:
     error: call to undeclared function 'getentropy'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            int r = getentropy(&result, sizeof(uint64_t));
```